// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: membership/v1/membership.proto

package membershipv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/raphaellaude/usaschooldata/api/membership/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MembershipServiceName is the fully-qualified name of the MembershipService service.
	MembershipServiceName = "membership.v1.MembershipService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MembershipServiceGetMembershipProcedure is the fully-qualified name of the MembershipService's
	// GetMembership RPC.
	MembershipServiceGetMembershipProcedure = "/membership.v1.MembershipService/GetMembership"
)

// MembershipServiceClient is a client for the membership.v1.MembershipService service.
type MembershipServiceClient interface {
	GetMembership(context.Context, *v1.GetMembershipRequest) (*v1.GetMembershipResponse, error)
}

// NewMembershipServiceClient constructs a client for the membership.v1.MembershipService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMembershipServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MembershipServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	membershipServiceMethods := v1.File_membership_v1_membership_proto.Services().ByName("MembershipService").Methods()
	return &membershipServiceClient{
		getMembership: connect.NewClient[v1.GetMembershipRequest, v1.GetMembershipResponse](
			httpClient,
			baseURL+MembershipServiceGetMembershipProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("GetMembership")),
			connect.WithClientOptions(opts...),
		),
	}
}

// membershipServiceClient implements MembershipServiceClient.
type membershipServiceClient struct {
	getMembership *connect.Client[v1.GetMembershipRequest, v1.GetMembershipResponse]
}

// GetMembership calls membership.v1.MembershipService.GetMembership.
func (c *membershipServiceClient) GetMembership(ctx context.Context, req *v1.GetMembershipRequest) (*v1.GetMembershipResponse, error) {
	response, err := c.getMembership.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// MembershipServiceHandler is an implementation of the membership.v1.MembershipService service.
type MembershipServiceHandler interface {
	GetMembership(context.Context, *v1.GetMembershipRequest) (*v1.GetMembershipResponse, error)
}

// NewMembershipServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMembershipServiceHandler(svc MembershipServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	membershipServiceMethods := v1.File_membership_v1_membership_proto.Services().ByName("MembershipService").Methods()
	membershipServiceGetMembershipHandler := connect.NewUnaryHandlerSimple(
		MembershipServiceGetMembershipProcedure,
		svc.GetMembership,
		connect.WithSchema(membershipServiceMethods.ByName("GetMembership")),
		connect.WithHandlerOptions(opts...),
	)
	return "/membership.v1.MembershipService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MembershipServiceGetMembershipProcedure:
			membershipServiceGetMembershipHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMembershipServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMembershipServiceHandler struct{}

func (UnimplementedMembershipServiceHandler) GetMembership(context.Context, *v1.GetMembershipRequest) (*v1.GetMembershipResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("membership.v1.MembershipService.GetMembership is not implemented"))
}
