// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: directory/v1/directory.proto

package directoryv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/raphaellaude/usaschooldata/api/directory/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DirectoryServiceName is the fully-qualified name of the DirectoryService service.
	DirectoryServiceName = "directory.v1.DirectoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DirectoryServiceGetMatchingSchoolsProcedure is the fully-qualified name of the DirectoryService's
	// GetMatchingSchools RPC.
	DirectoryServiceGetMatchingSchoolsProcedure = "/directory.v1.DirectoryService/GetMatchingSchools"
)

// DirectoryServiceClient is a client for the directory.v1.DirectoryService service.
type DirectoryServiceClient interface {
	GetMatchingSchools(context.Context, *v1.GetMatchingSchoolsRequest) (*v1.GetMatchingSchoolsResponse, error)
}

// NewDirectoryServiceClient constructs a client for the directory.v1.DirectoryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDirectoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DirectoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	directoryServiceMethods := v1.File_directory_v1_directory_proto.Services().ByName("DirectoryService").Methods()
	return &directoryServiceClient{
		getMatchingSchools: connect.NewClient[v1.GetMatchingSchoolsRequest, v1.GetMatchingSchoolsResponse](
			httpClient,
			baseURL+DirectoryServiceGetMatchingSchoolsProcedure,
			connect.WithSchema(directoryServiceMethods.ByName("GetMatchingSchools")),
			connect.WithClientOptions(opts...),
		),
	}
}

// directoryServiceClient implements DirectoryServiceClient.
type directoryServiceClient struct {
	getMatchingSchools *connect.Client[v1.GetMatchingSchoolsRequest, v1.GetMatchingSchoolsResponse]
}

// GetMatchingSchools calls directory.v1.DirectoryService.GetMatchingSchools.
func (c *directoryServiceClient) GetMatchingSchools(ctx context.Context, req *v1.GetMatchingSchoolsRequest) (*v1.GetMatchingSchoolsResponse, error) {
	response, err := c.getMatchingSchools.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DirectoryServiceHandler is an implementation of the directory.v1.DirectoryService service.
type DirectoryServiceHandler interface {
	GetMatchingSchools(context.Context, *v1.GetMatchingSchoolsRequest) (*v1.GetMatchingSchoolsResponse, error)
}

// NewDirectoryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDirectoryServiceHandler(svc DirectoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	directoryServiceMethods := v1.File_directory_v1_directory_proto.Services().ByName("DirectoryService").Methods()
	directoryServiceGetMatchingSchoolsHandler := connect.NewUnaryHandlerSimple(
		DirectoryServiceGetMatchingSchoolsProcedure,
		svc.GetMatchingSchools,
		connect.WithSchema(directoryServiceMethods.ByName("GetMatchingSchools")),
		connect.WithHandlerOptions(opts...),
	)
	return "/directory.v1.DirectoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DirectoryServiceGetMatchingSchoolsProcedure:
			directoryServiceGetMatchingSchoolsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDirectoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDirectoryServiceHandler struct{}

func (UnimplementedDirectoryServiceHandler) GetMatchingSchools(context.Context, *v1.GetMatchingSchoolsRequest) (*v1.GetMatchingSchoolsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("directory.v1.DirectoryService.GetMatchingSchools is not implemented"))
}
