// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v1/directory.proto

package directoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SchoolSearch        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDirectoryResponse) Reset() {
	*x = SearchDirectoryResponse{}
	mi := &file_directory_v1_directory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDirectoryResponse) ProtoMessage() {}

func (x *SearchDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDirectoryResponse.ProtoReflect.Descriptor instead.
func (*SearchDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{0}
}

func (x *SearchDirectoryResponse) GetResults() []*SchoolSearch {
	if x != nil {
		return x.Results
	}
	return nil
}

type SchoolSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ncessch       string                 `protobuf:"bytes,1,opt,name=ncessch,proto3" json:"ncessch,omitempty"`
	SchName       string                 `protobuf:"bytes,2,opt,name=sch_name,json=schName,proto3" json:"sch_name,omitempty"`
	SchoolYear    string                 `protobuf:"bytes,3,opt,name=school_year,json=schoolYear,proto3" json:"school_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolSearch) Reset() {
	*x = SchoolSearch{}
	mi := &file_directory_v1_directory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolSearch) ProtoMessage() {}

func (x *SchoolSearch) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolSearch.ProtoReflect.Descriptor instead.
func (*SchoolSearch) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{1}
}

func (x *SchoolSearch) GetNcessch() string {
	if x != nil {
		return x.Ncessch
	}
	return ""
}

func (x *SchoolSearch) GetSchName() string {
	if x != nil {
		return x.SchName
	}
	return ""
}

func (x *SchoolSearch) GetSchoolYear() string {
	if x != nil {
		return x.SchoolYear
	}
	return ""
}

type GetMatchingSchoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchingSchoolsRequest) Reset() {
	*x = GetMatchingSchoolsRequest{}
	mi := &file_directory_v1_directory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchingSchoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchingSchoolsRequest) ProtoMessage() {}

func (x *GetMatchingSchoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchingSchoolsRequest.ProtoReflect.Descriptor instead.
func (*GetMatchingSchoolsRequest) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{2}
}

func (x *GetMatchingSchoolsRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type GetMatchingSchoolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SchoolSearch        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchingSchoolsResponse) Reset() {
	*x = GetMatchingSchoolsResponse{}
	mi := &file_directory_v1_directory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchingSchoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchingSchoolsResponse) ProtoMessage() {}

func (x *GetMatchingSchoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchingSchoolsResponse.ProtoReflect.Descriptor instead.
func (*GetMatchingSchoolsResponse) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{3}
}

func (x *GetMatchingSchoolsResponse) GetResults() []*SchoolSearch {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_directory_v1_directory_proto protoreflect.FileDescriptor

const file_directory_v1_directory_proto_rawDesc = "" +
	"\n" +
	"\x1cdirectory/v1/directory.proto\x12\fdirectory.v1\"O\n" +
	"\x17SearchDirectoryResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.directory.v1.SchoolSearchR\aresults\"d\n" +
	"\fSchoolSearch\x12\x18\n" +
	"\ancessch\x18\x01 \x01(\tR\ancessch\x12\x19\n" +
	"\bsch_name\x18\x02 \x01(\tR\aschName\x12\x1f\n" +
	"\vschool_year\x18\x03 \x01(\tR\n" +
	"schoolYear\"<\n" +
	"\x19GetMatchingSchoolsRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\"R\n" +
	"\x1aGetMatchingSchoolsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.directory.v1.SchoolSearchR\aresults2{\n" +
	"\x10DirectoryService\x12g\n" +
	"\x12GetMatchingSchools\x12'.directory.v1.GetMatchingSchoolsRequest\x1a(.directory.v1.GetMatchingSchoolsResponseB\xb9\x01\n" +
	"\x10com.directory.v1B\x0eDirectoryProtoP\x01ZBgithub.com/raphaellaude/usaschooldata/api/directory/v1;directoryv1\xa2\x02\x03DXX\xaa\x02\fDirectory.V1\xca\x02\rDirectory_\\V1\xe2\x02\x19Directory_\\V1\\GPBMetadata\xea\x02\rDirectory::V1b\x06proto3"

var (
	file_directory_v1_directory_proto_rawDescOnce sync.Once
	file_directory_v1_directory_proto_rawDescData []byte
)

func file_directory_v1_directory_proto_rawDescGZIP() []byte {
	file_directory_v1_directory_proto_rawDescOnce.Do(func() {
		file_directory_v1_directory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v1_directory_proto_rawDesc), len(file_directory_v1_directory_proto_rawDesc)))
	})
	return file_directory_v1_directory_proto_rawDescData
}

var file_directory_v1_directory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_directory_v1_directory_proto_goTypes = []any{
	(*SearchDirectoryResponse)(nil),    // 0: directory.v1.SearchDirectoryResponse
	(*SchoolSearch)(nil),               // 1: directory.v1.SchoolSearch
	(*GetMatchingSchoolsRequest)(nil),  // 2: directory.v1.GetMatchingSchoolsRequest
	(*GetMatchingSchoolsResponse)(nil), // 3: directory.v1.GetMatchingSchoolsResponse
}
var file_directory_v1_directory_proto_depIdxs = []int32{
	1, // 0: directory.v1.SearchDirectoryResponse.results:type_name -> directory.v1.SchoolSearch
	1, // 1: directory.v1.GetMatchingSchoolsResponse.results:type_name -> directory.v1.SchoolSearch
	2, // 2: directory.v1.DirectoryService.GetMatchingSchools:input_type -> directory.v1.GetMatchingSchoolsRequest
	3, // 3: directory.v1.DirectoryService.GetMatchingSchools:output_type -> directory.v1.GetMatchingSchoolsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_directory_v1_directory_proto_init() }
func file_directory_v1_directory_proto_init() {
	if File_directory_v1_directory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v1_directory_proto_rawDesc), len(file_directory_v1_directory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_directory_v1_directory_proto_goTypes,
		DependencyIndexes: file_directory_v1_directory_proto_depIdxs,
		MessageInfos:      file_directory_v1_directory_proto_msgTypes,
	}.Build()
	File_directory_v1_directory_proto = out.File
	file_directory_v1_directory_proto_goTypes = nil
	file_directory_v1_directory_proto_depIdxs = nil
}
