// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: directory/v1/directory.proto

package directoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchoolSearch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ncessch       string                 `protobuf:"bytes,1,opt,name=ncessch,proto3" json:"ncessch,omitempty"`
	SchName       string                 `protobuf:"bytes,2,opt,name=sch_name,json=schName,proto3" json:"sch_name,omitempty"`
	SchoolYear    string                 `protobuf:"bytes,3,opt,name=school_year,json=schoolYear,proto3" json:"school_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchoolSearch) Reset() {
	*x = SchoolSearch{}
	mi := &file_directory_v1_directory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchoolSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchoolSearch) ProtoMessage() {}

func (x *SchoolSearch) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchoolSearch.ProtoReflect.Descriptor instead.
func (*SchoolSearch) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{0}
}

func (x *SchoolSearch) GetNcessch() string {
	if x != nil {
		return x.Ncessch
	}
	return ""
}

func (x *SchoolSearch) GetSchName() string {
	if x != nil {
		return x.SchName
	}
	return ""
}

func (x *SchoolSearch) GetSchoolYear() string {
	if x != nil {
		return x.SchoolYear
	}
	return ""
}

type GetMatchingSchoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchingSchoolsRequest) Reset() {
	*x = GetMatchingSchoolsRequest{}
	mi := &file_directory_v1_directory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchingSchoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchingSchoolsRequest) ProtoMessage() {}

func (x *GetMatchingSchoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchingSchoolsRequest.ProtoReflect.Descriptor instead.
func (*GetMatchingSchoolsRequest) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{1}
}

func (x *GetMatchingSchoolsRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type GetMatchingSchoolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SchoolSearch        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchingSchoolsResponse) Reset() {
	*x = GetMatchingSchoolsResponse{}
	mi := &file_directory_v1_directory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchingSchoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchingSchoolsResponse) ProtoMessage() {}

func (x *GetMatchingSchoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchingSchoolsResponse.ProtoReflect.Descriptor instead.
func (*GetMatchingSchoolsResponse) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{2}
}

func (x *GetMatchingSchoolsResponse) GetResults() []*SchoolSearch {
	if x != nil {
		return x.Results
	}
	return nil
}

type School struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SchoolYearNo    int32                  `protobuf:"varint,1,opt,name=school_year_no,json=schoolYearNo,proto3" json:"school_year_no,omitempty"`
	SchoolYear      string                 `protobuf:"bytes,2,opt,name=school_year,json=schoolYear,proto3" json:"school_year,omitempty"`
	Ncessch         string                 `protobuf:"bytes,3,opt,name=ncessch,proto3" json:"ncessch,omitempty"`
	SchName         string                 `protobuf:"bytes,4,opt,name=sch_name,json=schName,proto3" json:"sch_name,omitempty"`
	SchType         int32                  `protobuf:"varint,5,opt,name=sch_type,json=schType,proto3" json:"sch_type,omitempty"`
	SchLevel        string                 `protobuf:"bytes,6,opt,name=sch_level,json=schLevel,proto3" json:"sch_level,omitempty"`
	Charter         string                 `protobuf:"bytes,7,opt,name=charter,proto3" json:"charter,omitempty"`
	SyStatus        int32                  `protobuf:"varint,8,opt,name=sy_status,json=syStatus,proto3" json:"sy_status,omitempty"`
	SyStatusUpdated int32                  `protobuf:"varint,9,opt,name=sy_status_updated,json=syStatusUpdated,proto3" json:"sy_status_updated,omitempty"`
	StateCode       string                 `protobuf:"bytes,10,opt,name=state_code,json=stateCode,proto3" json:"state_code,omitempty"`
	StateLeaid      string                 `protobuf:"bytes,11,opt,name=state_leaid,json=stateLeaid,proto3" json:"state_leaid,omitempty"`
	Leaid           string                 `protobuf:"bytes,12,opt,name=leaid,proto3" json:"leaid,omitempty"`
	GradePk         *bool                  `protobuf:"varint,20,opt,name=grade_pk,json=gradePk,proto3,oneof" json:"grade_pk,omitempty"`
	GradeK          *bool                  `protobuf:"varint,21,opt,name=grade_k,json=gradeK,proto3,oneof" json:"grade_k,omitempty"`
	Grade_01        *bool                  `protobuf:"varint,22,opt,name=grade_01,json=grade01,proto3,oneof" json:"grade_01,omitempty"`
	Grade_02        *bool                  `protobuf:"varint,23,opt,name=grade_02,json=grade02,proto3,oneof" json:"grade_02,omitempty"`
	Grade_03        *bool                  `protobuf:"varint,24,opt,name=grade_03,json=grade03,proto3,oneof" json:"grade_03,omitempty"`
	Grade_04        *bool                  `protobuf:"varint,25,opt,name=grade_04,json=grade04,proto3,oneof" json:"grade_04,omitempty"`
	Grade_05        *bool                  `protobuf:"varint,26,opt,name=grade_05,json=grade05,proto3,oneof" json:"grade_05,omitempty"`
	Grade_06        *bool                  `protobuf:"varint,27,opt,name=grade_06,json=grade06,proto3,oneof" json:"grade_06,omitempty"`
	Grade_07        *bool                  `protobuf:"varint,28,opt,name=grade_07,json=grade07,proto3,oneof" json:"grade_07,omitempty"`
	Grade_08        *bool                  `protobuf:"varint,29,opt,name=grade_08,json=grade08,proto3,oneof" json:"grade_08,omitempty"`
	Grade_09        *bool                  `protobuf:"varint,30,opt,name=grade_09,json=grade09,proto3,oneof" json:"grade_09,omitempty"`
	Grade_10        *bool                  `protobuf:"varint,31,opt,name=grade_10,json=grade10,proto3,oneof" json:"grade_10,omitempty"`
	Grade_11        *bool                  `protobuf:"varint,32,opt,name=grade_11,json=grade11,proto3,oneof" json:"grade_11,omitempty"`
	Grade_12        *bool                  `protobuf:"varint,33,opt,name=grade_12,json=grade12,proto3,oneof" json:"grade_12,omitempty"`
	Grade_13        *bool                  `protobuf:"varint,34,opt,name=grade_13,json=grade13,proto3,oneof" json:"grade_13,omitempty"`
	Ungraded        *bool                  `protobuf:"varint,35,opt,name=ungraded,proto3,oneof" json:"ungraded,omitempty"`
	AdultEducation  *bool                  `protobuf:"varint,36,opt,name=adult_education,json=adultEducation,proto3,oneof" json:"adult_education,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *School) Reset() {
	*x = School{}
	mi := &file_directory_v1_directory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *School) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*School) ProtoMessage() {}

func (x *School) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use School.ProtoReflect.Descriptor instead.
func (*School) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{3}
}

func (x *School) GetSchoolYearNo() int32 {
	if x != nil {
		return x.SchoolYearNo
	}
	return 0
}

func (x *School) GetSchoolYear() string {
	if x != nil {
		return x.SchoolYear
	}
	return ""
}

func (x *School) GetNcessch() string {
	if x != nil {
		return x.Ncessch
	}
	return ""
}

func (x *School) GetSchName() string {
	if x != nil {
		return x.SchName
	}
	return ""
}

func (x *School) GetSchType() int32 {
	if x != nil {
		return x.SchType
	}
	return 0
}

func (x *School) GetSchLevel() string {
	if x != nil {
		return x.SchLevel
	}
	return ""
}

func (x *School) GetCharter() string {
	if x != nil {
		return x.Charter
	}
	return ""
}

func (x *School) GetSyStatus() int32 {
	if x != nil {
		return x.SyStatus
	}
	return 0
}

func (x *School) GetSyStatusUpdated() int32 {
	if x != nil {
		return x.SyStatusUpdated
	}
	return 0
}

func (x *School) GetStateCode() string {
	if x != nil {
		return x.StateCode
	}
	return ""
}

func (x *School) GetStateLeaid() string {
	if x != nil {
		return x.StateLeaid
	}
	return ""
}

func (x *School) GetLeaid() string {
	if x != nil {
		return x.Leaid
	}
	return ""
}

func (x *School) GetGradePk() bool {
	if x != nil && x.GradePk != nil {
		return *x.GradePk
	}
	return false
}

func (x *School) GetGradeK() bool {
	if x != nil && x.GradeK != nil {
		return *x.GradeK
	}
	return false
}

func (x *School) GetGrade_01() bool {
	if x != nil && x.Grade_01 != nil {
		return *x.Grade_01
	}
	return false
}

func (x *School) GetGrade_02() bool {
	if x != nil && x.Grade_02 != nil {
		return *x.Grade_02
	}
	return false
}

func (x *School) GetGrade_03() bool {
	if x != nil && x.Grade_03 != nil {
		return *x.Grade_03
	}
	return false
}

func (x *School) GetGrade_04() bool {
	if x != nil && x.Grade_04 != nil {
		return *x.Grade_04
	}
	return false
}

func (x *School) GetGrade_05() bool {
	if x != nil && x.Grade_05 != nil {
		return *x.Grade_05
	}
	return false
}

func (x *School) GetGrade_06() bool {
	if x != nil && x.Grade_06 != nil {
		return *x.Grade_06
	}
	return false
}

func (x *School) GetGrade_07() bool {
	if x != nil && x.Grade_07 != nil {
		return *x.Grade_07
	}
	return false
}

func (x *School) GetGrade_08() bool {
	if x != nil && x.Grade_08 != nil {
		return *x.Grade_08
	}
	return false
}

func (x *School) GetGrade_09() bool {
	if x != nil && x.Grade_09 != nil {
		return *x.Grade_09
	}
	return false
}

func (x *School) GetGrade_10() bool {
	if x != nil && x.Grade_10 != nil {
		return *x.Grade_10
	}
	return false
}

func (x *School) GetGrade_11() bool {
	if x != nil && x.Grade_11 != nil {
		return *x.Grade_11
	}
	return false
}

func (x *School) GetGrade_12() bool {
	if x != nil && x.Grade_12 != nil {
		return *x.Grade_12
	}
	return false
}

func (x *School) GetGrade_13() bool {
	if x != nil && x.Grade_13 != nil {
		return *x.Grade_13
	}
	return false
}

func (x *School) GetUngraded() bool {
	if x != nil && x.Ungraded != nil {
		return *x.Ungraded
	}
	return false
}

func (x *School) GetAdultEducation() bool {
	if x != nil && x.AdultEducation != nil {
		return *x.AdultEducation
	}
	return false
}

type GetSchoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ncessch       string                 `protobuf:"bytes,1,opt,name=ncessch,proto3" json:"ncessch,omitempty"`
	SchoolYear    string                 `protobuf:"bytes,2,opt,name=school_year,json=schoolYear,proto3" json:"school_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchoolRequest) Reset() {
	*x = GetSchoolRequest{}
	mi := &file_directory_v1_directory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolRequest) ProtoMessage() {}

func (x *GetSchoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolRequest.ProtoReflect.Descriptor instead.
func (*GetSchoolRequest) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{4}
}

func (x *GetSchoolRequest) GetNcessch() string {
	if x != nil {
		return x.Ncessch
	}
	return ""
}

func (x *GetSchoolRequest) GetSchoolYear() string {
	if x != nil {
		return x.SchoolYear
	}
	return ""
}

type GetSchoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	School        *School                `protobuf:"bytes,1,opt,name=school,proto3" json:"school,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchoolResponse) Reset() {
	*x = GetSchoolResponse{}
	mi := &file_directory_v1_directory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchoolResponse) ProtoMessage() {}

func (x *GetSchoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_directory_v1_directory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchoolResponse.ProtoReflect.Descriptor instead.
func (*GetSchoolResponse) Descriptor() ([]byte, []int) {
	return file_directory_v1_directory_proto_rawDescGZIP(), []int{5}
}

func (x *GetSchoolResponse) GetSchool() *School {
	if x != nil {
		return x.School
	}
	return nil
}

var File_directory_v1_directory_proto protoreflect.FileDescriptor

const file_directory_v1_directory_proto_rawDesc = "" +
	"\n" +
	"\x1cdirectory/v1/directory.proto\x12\fdirectory.v1\"d\n" +
	"\fSchoolSearch\x12\x18\n" +
	"\ancessch\x18\x01 \x01(\tR\ancessch\x12\x19\n" +
	"\bsch_name\x18\x02 \x01(\tR\aschName\x12\x1f\n" +
	"\vschool_year\x18\x03 \x01(\tR\n" +
	"schoolYear\"<\n" +
	"\x19GetMatchingSchoolsRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\"R\n" +
	"\x1aGetMatchingSchoolsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.directory.v1.SchoolSearchR\aresults\"\x85\t\n" +
	"\x06School\x12$\n" +
	"\x0eschool_year_no\x18\x01 \x01(\x05R\fschoolYearNo\x12\x1f\n" +
	"\vschool_year\x18\x02 \x01(\tR\n" +
	"schoolYear\x12\x18\n" +
	"\ancessch\x18\x03 \x01(\tR\ancessch\x12\x19\n" +
	"\bsch_name\x18\x04 \x01(\tR\aschName\x12\x19\n" +
	"\bsch_type\x18\x05 \x01(\x05R\aschType\x12\x1b\n" +
	"\tsch_level\x18\x06 \x01(\tR\bschLevel\x12\x18\n" +
	"\acharter\x18\a \x01(\tR\acharter\x12\x1b\n" +
	"\tsy_status\x18\b \x01(\x05R\bsyStatus\x12*\n" +
	"\x11sy_status_updated\x18\t \x01(\x05R\x0fsyStatusUpdated\x12\x1d\n" +
	"\n" +
	"state_code\x18\n" +
	" \x01(\tR\tstateCode\x12\x1f\n" +
	"\vstate_leaid\x18\v \x01(\tR\n" +
	"stateLeaid\x12\x14\n" +
	"\x05leaid\x18\f \x01(\tR\x05leaid\x12\x1e\n" +
	"\bgrade_pk\x18\x14 \x01(\bH\x00R\agradePk\x88\x01\x01\x12\x1c\n" +
	"\agrade_k\x18\x15 \x01(\bH\x01R\x06gradeK\x88\x01\x01\x12\x1e\n" +
	"\bgrade_01\x18\x16 \x01(\bH\x02R\agrade01\x88\x01\x01\x12\x1e\n" +
	"\bgrade_02\x18\x17 \x01(\bH\x03R\agrade02\x88\x01\x01\x12\x1e\n" +
	"\bgrade_03\x18\x18 \x01(\bH\x04R\agrade03\x88\x01\x01\x12\x1e\n" +
	"\bgrade_04\x18\x19 \x01(\bH\x05R\agrade04\x88\x01\x01\x12\x1e\n" +
	"\bgrade_05\x18\x1a \x01(\bH\x06R\agrade05\x88\x01\x01\x12\x1e\n" +
	"\bgrade_06\x18\x1b \x01(\bH\aR\agrade06\x88\x01\x01\x12\x1e\n" +
	"\bgrade_07\x18\x1c \x01(\bH\bR\agrade07\x88\x01\x01\x12\x1e\n" +
	"\bgrade_08\x18\x1d \x01(\bH\tR\agrade08\x88\x01\x01\x12\x1e\n" +
	"\bgrade_09\x18\x1e \x01(\bH\n" +
	"R\agrade09\x88\x01\x01\x12\x1e\n" +
	"\bgrade_10\x18\x1f \x01(\bH\vR\agrade10\x88\x01\x01\x12\x1e\n" +
	"\bgrade_11\x18  \x01(\bH\fR\agrade11\x88\x01\x01\x12\x1e\n" +
	"\bgrade_12\x18! \x01(\bH\rR\agrade12\x88\x01\x01\x12\x1e\n" +
	"\bgrade_13\x18\" \x01(\bH\x0eR\agrade13\x88\x01\x01\x12\x1f\n" +
	"\bungraded\x18# \x01(\bH\x0fR\bungraded\x88\x01\x01\x12,\n" +
	"\x0fadult_education\x18$ \x01(\bH\x10R\x0eadultEducation\x88\x01\x01B\v\n" +
	"\t_grade_pkB\n" +
	"\n" +
	"\b_grade_kB\v\n" +
	"\t_grade_01B\v\n" +
	"\t_grade_02B\v\n" +
	"\t_grade_03B\v\n" +
	"\t_grade_04B\v\n" +
	"\t_grade_05B\v\n" +
	"\t_grade_06B\v\n" +
	"\t_grade_07B\v\n" +
	"\t_grade_08B\v\n" +
	"\t_grade_09B\v\n" +
	"\t_grade_10B\v\n" +
	"\t_grade_11B\v\n" +
	"\t_grade_12B\v\n" +
	"\t_grade_13B\v\n" +
	"\t_ungradedB\x12\n" +
	"\x10_adult_education\"M\n" +
	"\x10GetSchoolRequest\x12\x18\n" +
	"\ancessch\x18\x01 \x01(\tR\ancessch\x12\x1f\n" +
	"\vschool_year\x18\x02 \x01(\tR\n" +
	"schoolYear\"A\n" +
	"\x11GetSchoolResponse\x12,\n" +
	"\x06school\x18\x01 \x01(\v2\x14.directory.v1.SchoolR\x06school2\xc9\x01\n" +
	"\x10DirectoryService\x12g\n" +
	"\x12GetMatchingSchools\x12'.directory.v1.GetMatchingSchoolsRequest\x1a(.directory.v1.GetMatchingSchoolsResponse\x12L\n" +
	"\tGetSchool\x12\x1e.directory.v1.GetSchoolRequest\x1a\x1f.directory.v1.GetSchoolResponseB\xb9\x01\n" +
	"\x10com.directory.v1B\x0eDirectoryProtoP\x01ZBgithub.com/raphaellaude/usaschooldata/api/directory/v1;directoryv1\xa2\x02\x03DXX\xaa\x02\fDirectory.V1\xca\x02\rDirectory_\\V1\xe2\x02\x19Directory_\\V1\\GPBMetadata\xea\x02\rDirectory::V1b\x06proto3"

var (
	file_directory_v1_directory_proto_rawDescOnce sync.Once
	file_directory_v1_directory_proto_rawDescData []byte
)

func file_directory_v1_directory_proto_rawDescGZIP() []byte {
	file_directory_v1_directory_proto_rawDescOnce.Do(func() {
		file_directory_v1_directory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_directory_v1_directory_proto_rawDesc), len(file_directory_v1_directory_proto_rawDesc)))
	})
	return file_directory_v1_directory_proto_rawDescData
}

var file_directory_v1_directory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_directory_v1_directory_proto_goTypes = []any{
	(*SchoolSearch)(nil),               // 0: directory.v1.SchoolSearch
	(*GetMatchingSchoolsRequest)(nil),  // 1: directory.v1.GetMatchingSchoolsRequest
	(*GetMatchingSchoolsResponse)(nil), // 2: directory.v1.GetMatchingSchoolsResponse
	(*School)(nil),                     // 3: directory.v1.School
	(*GetSchoolRequest)(nil),           // 4: directory.v1.GetSchoolRequest
	(*GetSchoolResponse)(nil),          // 5: directory.v1.GetSchoolResponse
}
var file_directory_v1_directory_proto_depIdxs = []int32{
	0, // 0: directory.v1.GetMatchingSchoolsResponse.results:type_name -> directory.v1.SchoolSearch
	3, // 1: directory.v1.GetSchoolResponse.school:type_name -> directory.v1.School
	1, // 2: directory.v1.DirectoryService.GetMatchingSchools:input_type -> directory.v1.GetMatchingSchoolsRequest
	4, // 3: directory.v1.DirectoryService.GetSchool:input_type -> directory.v1.GetSchoolRequest
	2, // 4: directory.v1.DirectoryService.GetMatchingSchools:output_type -> directory.v1.GetMatchingSchoolsResponse
	5, // 5: directory.v1.DirectoryService.GetSchool:output_type -> directory.v1.GetSchoolResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_directory_v1_directory_proto_init() }
func file_directory_v1_directory_proto_init() {
	if File_directory_v1_directory_proto != nil {
		return
	}
	file_directory_v1_directory_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_directory_v1_directory_proto_rawDesc), len(file_directory_v1_directory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_directory_v1_directory_proto_goTypes,
		DependencyIndexes: file_directory_v1_directory_proto_depIdxs,
		MessageInfos:      file_directory_v1_directory_proto_msgTypes,
	}.Build()
	File_directory_v1_directory_proto = out.File
	file_directory_v1_directory_proto_goTypes = nil
	file_directory_v1_directory_proto_depIdxs = nil
}
