// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: membership/v1/membership.proto

package membershipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMembershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByYear        []*TotalEnrollment     `protobuf:"bytes,1,rep,name=by_year,json=byYear,proto3" json:"by_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipResponse) Reset() {
	*x = GetMembershipResponse{}
	mi := &file_membership_v1_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipResponse) ProtoMessage() {}

func (x *GetMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipResponse.ProtoReflect.Descriptor instead.
func (*GetMembershipResponse) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{0}
}

func (x *GetMembershipResponse) GetByYear() []*TotalEnrollment {
	if x != nil {
		return x.ByYear
	}
	return nil
}

type TotalEnrollment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SchoolYear      string                 `protobuf:"bytes,1,opt,name=school_year,json=schoolYear,proto3" json:"school_year,omitempty"`
	TotalEnrollment int32                  `protobuf:"varint,2,opt,name=total_enrollment,json=totalEnrollment,proto3" json:"total_enrollment,omitempty"`
	Male            int32                  `protobuf:"varint,3,opt,name=male,proto3" json:"male,omitempty"`
	Female          int32                  `protobuf:"varint,4,opt,name=female,proto3" json:"female,omitempty"`
	NativeAmerican  int32                  `protobuf:"varint,5,opt,name=native_american,json=nativeAmerican,proto3" json:"native_american,omitempty"`
	Asian           int32                  `protobuf:"varint,6,opt,name=asian,proto3" json:"asian,omitempty"`
	Black           int32                  `protobuf:"varint,7,opt,name=black,proto3" json:"black,omitempty"`
	Hispanic        int32                  `protobuf:"varint,8,opt,name=hispanic,proto3" json:"hispanic,omitempty"`
	PacificIslander int32                  `protobuf:"varint,9,opt,name=pacific_islander,json=pacificIslander,proto3" json:"pacific_islander,omitempty"`
	Multiracial     int32                  `protobuf:"varint,10,opt,name=multiracial,proto3" json:"multiracial,omitempty"`
	White           int32                  `protobuf:"varint,11,opt,name=white,proto3" json:"white,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TotalEnrollment) Reset() {
	*x = TotalEnrollment{}
	mi := &file_membership_v1_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalEnrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalEnrollment) ProtoMessage() {}

func (x *TotalEnrollment) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalEnrollment.ProtoReflect.Descriptor instead.
func (*TotalEnrollment) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{1}
}

func (x *TotalEnrollment) GetSchoolYear() string {
	if x != nil {
		return x.SchoolYear
	}
	return ""
}

func (x *TotalEnrollment) GetTotalEnrollment() int32 {
	if x != nil {
		return x.TotalEnrollment
	}
	return 0
}

func (x *TotalEnrollment) GetMale() int32 {
	if x != nil {
		return x.Male
	}
	return 0
}

func (x *TotalEnrollment) GetFemale() int32 {
	if x != nil {
		return x.Female
	}
	return 0
}

func (x *TotalEnrollment) GetNativeAmerican() int32 {
	if x != nil {
		return x.NativeAmerican
	}
	return 0
}

func (x *TotalEnrollment) GetAsian() int32 {
	if x != nil {
		return x.Asian
	}
	return 0
}

func (x *TotalEnrollment) GetBlack() int32 {
	if x != nil {
		return x.Black
	}
	return 0
}

func (x *TotalEnrollment) GetHispanic() int32 {
	if x != nil {
		return x.Hispanic
	}
	return 0
}

func (x *TotalEnrollment) GetPacificIslander() int32 {
	if x != nil {
		return x.PacificIslander
	}
	return 0
}

func (x *TotalEnrollment) GetMultiracial() int32 {
	if x != nil {
		return x.Multiracial
	}
	return 0
}

func (x *TotalEnrollment) GetWhite() int32 {
	if x != nil {
		return x.White
	}
	return 0
}

type GetMembershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ncessch       string                 `protobuf:"bytes,1,opt,name=ncessch,proto3" json:"ncessch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMembershipRequest) Reset() {
	*x = GetMembershipRequest{}
	mi := &file_membership_v1_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMembershipRequest) ProtoMessage() {}

func (x *GetMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_membership_v1_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMembershipRequest.ProtoReflect.Descriptor instead.
func (*GetMembershipRequest) Descriptor() ([]byte, []int) {
	return file_membership_v1_membership_proto_rawDescGZIP(), []int{2}
}

func (x *GetMembershipRequest) GetNcessch() string {
	if x != nil {
		return x.Ncessch
	}
	return ""
}

var File_membership_v1_membership_proto protoreflect.FileDescriptor

const file_membership_v1_membership_proto_rawDesc = "" +
	"\n" +
	"\x1emembership/v1/membership.proto\x12\rmembership.v1\"P\n" +
	"\x15GetMembershipResponse\x127\n" +
	"\aby_year\x18\x01 \x03(\v2\x1e.membership.v1.TotalEnrollmentR\x06byYear\"\xdd\x02\n" +
	"\x0fTotalEnrollment\x12\x1f\n" +
	"\vschool_year\x18\x01 \x01(\tR\n" +
	"schoolYear\x12)\n" +
	"\x10total_enrollment\x18\x02 \x01(\x05R\x0ftotalEnrollment\x12\x12\n" +
	"\x04male\x18\x03 \x01(\x05R\x04male\x12\x16\n" +
	"\x06female\x18\x04 \x01(\x05R\x06female\x12'\n" +
	"\x0fnative_american\x18\x05 \x01(\x05R\x0enativeAmerican\x12\x14\n" +
	"\x05asian\x18\x06 \x01(\x05R\x05asian\x12\x14\n" +
	"\x05black\x18\a \x01(\x05R\x05black\x12\x1a\n" +
	"\bhispanic\x18\b \x01(\x05R\bhispanic\x12)\n" +
	"\x10pacific_islander\x18\t \x01(\x05R\x0fpacificIslander\x12 \n" +
	"\vmultiracial\x18\n" +
	" \x01(\x05R\vmultiracial\x12\x14\n" +
	"\x05white\x18\v \x01(\x05R\x05white\"0\n" +
	"\x14GetMembershipRequest\x12\x18\n" +
	"\ancessch\x18\x01 \x01(\tR\ancessch2o\n" +
	"\x11MembershipService\x12Z\n" +
	"\rGetMembership\x12#.membership.v1.GetMembershipRequest\x1a$.membership.v1.GetMembershipResponseB\xbf\x01\n" +
	"\x11com.membership.v1B\x0fMembershipProtoP\x01ZDgithub.com/raphaellaude/usaschooldata/api/membership/v1;membershipv1\xa2\x02\x03MXX\xaa\x02\rMembership.V1\xca\x02\rMembership\\V1\xe2\x02\x19Membership\\V1\\GPBMetadata\xea\x02\x0eMembership::V1b\x06proto3"

var (
	file_membership_v1_membership_proto_rawDescOnce sync.Once
	file_membership_v1_membership_proto_rawDescData []byte
)

func file_membership_v1_membership_proto_rawDescGZIP() []byte {
	file_membership_v1_membership_proto_rawDescOnce.Do(func() {
		file_membership_v1_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_membership_v1_membership_proto_rawDesc), len(file_membership_v1_membership_proto_rawDesc)))
	})
	return file_membership_v1_membership_proto_rawDescData
}

var file_membership_v1_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_membership_v1_membership_proto_goTypes = []any{
	(*GetMembershipResponse)(nil), // 0: membership.v1.GetMembershipResponse
	(*TotalEnrollment)(nil),       // 1: membership.v1.TotalEnrollment
	(*GetMembershipRequest)(nil),  // 2: membership.v1.GetMembershipRequest
}
var file_membership_v1_membership_proto_depIdxs = []int32{
	1, // 0: membership.v1.GetMembershipResponse.by_year:type_name -> membership.v1.TotalEnrollment
	2, // 1: membership.v1.MembershipService.GetMembership:input_type -> membership.v1.GetMembershipRequest
	0, // 2: membership.v1.MembershipService.GetMembership:output_type -> membership.v1.GetMembershipResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_membership_v1_membership_proto_init() }
func file_membership_v1_membership_proto_init() {
	if File_membership_v1_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_membership_v1_membership_proto_rawDesc), len(file_membership_v1_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_membership_v1_membership_proto_goTypes,
		DependencyIndexes: file_membership_v1_membership_proto_depIdxs,
		MessageInfos:      file_membership_v1_membership_proto_msgTypes,
	}.Build()
	File_membership_v1_membership_proto = out.File
	file_membership_v1_membership_proto_goTypes = nil
	file_membership_v1_membership_proto_depIdxs = nil
}
